# Generated by Django 4.1.3 on 2022-11-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_emil_info_emial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='emial',
            new_name='email',
        ),
    ]
